fixtures:
  repositories:
    #corosync: 'https://github.com/puppetlabs/puppetlabs-corosync.git'
    #pacemaker: 'https://github.com/puppet-community/puppet-corosync'
    #stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'

  symlinks:
    pcs_fencing: "#{source_dir}"
    corosync: "#{source_dir}/../corosync"
    pacemaker: "#{source_dir}/../pacemaker"
    stdlib: "#{source_dir}/../stdlib"
