source 'https://rubygems.org'

group :development, :test do
  gem 'rspec-puppet',           :require => false
  gem 'puppetlabs_spec_helper', :require => false
  gem 'puppet-lint', '~> 1.1.0'
  gem 'rake', '~> 10.1.0',      :require => false
  gem 'rspec', '~> 3.3.0',       :require => false
  gem 'json'
  gem 'webmock'
end

if puppetversion = ENV['PUPPET_GEM_VERSION']
  gem 'puppet', puppetversion, :require => false
else
  gem 'puppet', :require => false
end
