#!/bin/bash

set -eux

ROOT="$(dirname `readlink -f $0`)"
MODULES="${ROOT}"/deployment_scripts/puppet/modules/
TMP_DIR="${ROOT}"/tmp/
mkdir -p "${MODULES}"
mkdir -p "${TMP_DIR}"
#Puppetlabs/stdlib 4.5.0
REPO_PATH='https://github.com/puppetlabs/puppetlabs-stdlib/tarball/80f09623b63cf6946b5913b629911e2c49b5d1dd'

wget -qO- "${REPO_PATH}" | \
    tar -C "${TMP_DIR}" -zxvf - \
    puppetlabs-puppetlabs-stdlib-80f0962 && \
    cp -Rf "${TMP_DIR}puppetlabs-puppetlabs-stdlib-80f0962" "${MODULES}stdlib"

#Puppet-community/puppet-corosync 0.8.0
REPO_PATH='https://github.com/puppet-community/puppet-corosync/tarball/88e267b00add700aeb0f4dae301bd327a8b18b54'

wget -qO- "${REPO_PATH}" | \
    tar -C "${TMP_DIR}" -zxvf - \
    puppet-community-puppet-corosync-88e267b && \
    cp -Rf "${TMP_DIR}puppet-community-puppet-corosync-88e267b" "${MODULES}corosync"

#Fuel 7.0 pacemaker
REPO_PATH='https://github.com/openstack/fuel-library/tarball/5d50055aeca1dd0dc53b43825dc4c8f7780be9dd'

wget -qO- "${REPO_PATH}" | \
    tar -C "${TMP_DIR}" --strip-components=3 -zxvf - \
    openstack-fuel-library-5d50055 && \
    cp -Rf "${TMP_DIR}pacemaker" "${MODULES}pacemaker"

